
# Spring Configuration
server:
    port: ${API_PORT:8083}
    devtools:
        add-properties: false

# PostgreSQL Configuration
spring:
    datasource:
        driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
        url: ${DB_URL:jdbc:postgresql://localhost:5432/demo}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:password}

# MyBatis Configuration
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.week2

