# pure java - Class Loading

week1:
    class: com.example.week1.test01.YamlRunner

# PostgreSQL Configuration
spring:
    datasource:
        driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
        url: ${DB_URL:jdbc:postgresql://localhost:5432/demo}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:password}

# MyBatis
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.week1.dummy.domain.model
