# pure java - Class Loading
week1:
    class: com.example.week1.test03.YamlRunner

# Spring Configuration
server:
    port: ${API_PORT:8082}
    devtools:
        add-properties: false

# PostgreSQL Configuration
spring:
    datasource:
        driver-class-name: ${DB_DRIVER:org.postgresql.Driver}
        url: ${DB_URL:jdbc:postgresql://localhost:5432/demo}
        username: ${DB_USERNAME:postgres}
        password: ${DB_PASSWORD:password}

# MyBatis Configuration
mybatis:
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.example.week1.common.database.model, com.example.week1.dummy.database.model

# test01.workflow.Scheduler
scheduler:
    fixedRate: 5000
    poolSize: 5
    threadNamePrefix: ScheduledTask-
executor:
    corePoolSize: 5
    maxPoolSize: 10
    queueCapacity: 50
    threadNamePrefix: ThreadPoolExecutor-

# test02.workflow.Scheduler
jobs:
    cron-exp: "*/10 * * * * *"
