name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      cache-hit: ${{ steps.cache.outputs.cache-hit }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '17'
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

  build:
    runs-on: ubuntu-latest
    needs: setup
    steps:
    - name: Build with Maven
      run: mvn -B clean install

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Run tests with Maven
      run: mvn test

  # checkstyle:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: Checkstyle
  #     run: mvn checkstyle:checkstyle

  # pmd:
  #   runs-on: ubuntu-latest
  #   needs: build
  #   steps:
  #   - name: PMD
  #     run: mvn pmd:pmd

  spotbugs:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: SpotBugs
      run: mvn spotbugs:check
